# Generated by Django 5.2.5 on 2026-01-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_usd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangerate",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
            preserve_default=False,
        ),
    ]
